// PointCloudBA.cpp
//
// libtorch-backed differentiable point-cloud refinement. See PointCloudBA.h
// for the design rationale. All real work is guarded by SPLATSHOP_HAS_LIBTORCH;
// the stub in the header covers the missing-dependency build.

// Include order matters: PointCloudBA.h pulls in HostDeviceInterface.h, which
// uses CUDA handle types (CUsurfObject, CUtexObject) and Splatshop headers
// that use `vec3 min`/`vec3 max`. The CUDA headers must be visible first, and
// on Windows the min/max macros from Windows.h (pulled in transitively by
// libtorch) must be suppressed with NOMINMAX so those member names resolve.
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#endif

#include <cuda.h>
#include <cuda_runtime.h>
#include "CURuntime.h"

#include "PointCloudBA.h"

#ifdef SPLATSHOP_HAS_LIBTORCH

#include <torch/torch.h>
#include <c10/cuda/CUDAStream.h>

#include <cmath>
#include <algorithm>

namespace optim {

using torch::Tensor;
using torch::TensorOptions;

namespace {

// ---- small autograd helpers (kept local; libtorch C++ API) ----

inline TensorOptions opts() {
    return TensorOptions().dtype(torch::kFloat32).device(torch::kCUDA);
}

// 1D Gaussian window of size `win`, normalized to sum 1. Used for SSIM.
Tensor gaussianWindow1d(int win, float sigma) {
    auto t = torch::arange(win, TensorOptions().dtype(torch::kFloat32))
                 - float(win - 1) / 2.f;
    auto g = torch::exp(-(t * t) / (2.f * sigma * sigma));
    return g / g.sum();
}

// SSIM(x, y) over a single channel using a win x win Gaussian window.
Tensor ssimSingleChannel(const Tensor& x0, const Tensor& y0, int win, float sigma) {
    auto x = x0.unsqueeze(0).unsqueeze(0);  // [1,1,H,W]
    auto y = y0.unsqueeze(0).unsqueeze(0);

    auto g1 = gaussianWindow1d(win, sigma);
    auto window = (g1.unsqueeze(0) * g1.unsqueeze(1))
                      .unsqueeze(0).unsqueeze(0).to(x);  // [1,1,win,win]

    constexpr float C1 = 0.01f * 0.01f;
    constexpr float C2 = 0.03f * 0.03f;

    int pad = win / 2;
    auto muX  = torch::conv2d(x,      window, /*bias=*/{}, /*stride=*/{}, pad);
    auto muY  = torch::conv2d(y,      window, {}, {}, pad);
    auto muX2 = muX * muX;
    auto muY2 = muY * muY;
    auto muXY = muX * muY;

    auto sigmaX2 = torch::conv2d(x * x, window, {}, {}, pad) - muX2;
    auto sigmaY2 = torch::conv2d(y * y, window, {}, {}, pad) - muY2;
    auto sigmaXY = torch::conv2d(x * y, window, {}, {}, pad) - muXY;

    auto ssimMap =
        ((2.f * muXY + C1) * (2.f * sigmaXY + C2)) /
        ((muX2 + muY2 + C1) * (sigmaX2 + sigmaY2 + C2));
    return ssimMap.mean();
}

// ---------------------------------------------------------------------------
// Differentiable EWA Gaussian-splatting forward pass (fully vectorized).
//
// Each Gaussian i contributes to pixels within a fixed screen-space radius R
// a weight  w = alpha_i * exp(-0.5 * d2 / sigma_i^2)  where d2 is the squared
// pixel distance to the projected centre and alpha_i = sigmoid(opacity_i).
// The rendered colour is the normalized weighted sum
//     C(p) = sum_i w_i c_i / (sum_i w_i + eps).
//
// Implementation: for every splat, a (2R+1)x(2R+1) patch of pixel offsets is
// generated by broadcasting, the per-pair weights and colour contributions are
// computed as GPU tensors, then scattered into per-pixel accumulators via
// `scatter_add_`. No per-splat CPU loop or `.item()` sync — the entire pass
// is a sequence of vectorized tensor ops so autograd records the full graph.
//
// What is differentiable: weight w (→ position via projection, scale via
// sigma, opacity via alpha) and the colour contribution w*c (→ color). The
// integer pixel index (which pixels a splat touches) is treated as a constant
// — the standard approximation used in tile-based differentiable splatting.
// ---------------------------------------------------------------------------
Tensor renderGaussians(
    const Tensor& position,   // [N,3]
    const Tensor& color,      // [N,3]
    const Tensor& scale,      // [N,1] log-space isotropic
    const Tensor& opacity,    // [N,1] logit
    const Tensor& view,       // [4,4]
    float fx, float fy, float cx, float cy,
    int W, int H,
    int pixelRadius)          // fixed screen radius R (pixels)
{
    auto o = opts();
    int64_t N = position.size(0);
    int K = 2 * pixelRadius + 1;

    // --- Project centres to the image plane ---
    auto ones = torch::ones({N, 1}, o);
    auto pHom = torch::cat({position, ones}, /*dim=*/1);   // [N,4]
    auto pCam = pHom.mm(view.t());                          // [N,4]
    auto z = pCam.slice(1, 2, 3).clamp_min(1e-4f);          // [N,1]
    auto xy = pCam.slice(1, 0, 2) / z;                      // [N,2]
    auto sx = xy.slice(1, 0, 1) * fx + cx;                  // [N,1]
    auto sy = xy.slice(1, 1, 2) * fy + cy;                  // [N,1]

    // --- Per-splat screen sigma (pixels) from world scale ---
    auto sigmaScreen = (scale.exp() * (fx / z)).clamp_min(1e-3f);  // [N,1]
    auto inv2s2 = 0.5f / (sigmaScreen * sigmaScreen + 1e-12f);     // [N,1]

    // --- Build the (2R+1)^2 patch of pixel offsets per splat ---
    auto offsets = torch::arange(-pixelRadius, pixelRadius + 1, o);  // [K]
    // d2[i, dy, dx] = dx^2 + dy^2  (same for every splat)
    auto dx2 = offsets * offsets;                                // [K]
    auto d2 = (dx2.view({1, K, 1}) + dx2.view({1, 1, K}));       // [1,K,K]

    // Per-splat pixel coordinates: [N, K, K] via broadcasting
    //   px[n, dy, dx] = sx[n] + dx,  py[n, dy, dx] = sy[n] + dy
    auto px = sx.unsqueeze(2) + offsets.view({1, 1, K});   // [N,1,K] + [1,1,K] → [N,K,K]... need care
    auto py = sy.unsqueeze(2) + offsets.view({1, 1, K});
    // Correct the broadcast: sx is [N,1], offsets along x should broadcast over the last dim,
    // and offsets along y over the middle dim. Rebuild explicitly:
    px = sx + offsets.view({1, 1, K});   // [N,1] + [1,1,K] → [N,1,K] then broadcast to [N,K,K] later
    py = sy + offsets.view({1, K, 1});   // [N,1] + [1,K,1] → [N,K,1]
    // Expand to full [N, K, K]:
    px = px.expand({N, K, K});
    py = py.expand({N, K, K});

    // --- Weight per (splat, pixel) pair ---
    auto alpha = torch::sigmoid(opacity);                   // [N,1]
    // w = alpha * exp(-d2 * inv2s2), broadcasting [N,1] * [1,K,K] * [N,1,1,1]→[N,K,K]
    auto w = alpha.view({N, 1, 1}) *
             torch::exp(-d2.view({1, K, K}) * inv2s2.view({N, 1, 1}));  // [N,K,K]

    // --- Validity mask: pixel in bounds and z > 0 ---
    auto valid = (px >= 0) & (px < float(W)) & (py >= 0) & (py < float(H));
    w = w * valid.to(o.dtype(torch::kFloat32));

    // --- Flatten for scatter_add ---
    auto wFlat   = w.reshape(-1);                                   // [N*K*K]
    auto pxFloor = px.clamp(0.f, float(W - 1)).to(torch::kLong);    // [N,K,K]
    auto pyFloor = py.clamp(0.f, float(H - 1)).to(torch::kLong);
    auto idxFlat = (pyFloor * W + pxFloor).reshape(-1);             // [N*K*K]

    // Colour per pair: broadcast color [N,3] → [N,K,K,3] → [N*K*K, 3]
    auto colorRep = color.view({N, 1, 1, 3}).expand({N, K, K, 3})
                          .reshape({N * K * K, 3});
    auto src = wFlat.unsqueeze(1) * colorRep;                       // [N*K*K, 3]

    // --- Scatter into per-pixel accumulators ---
    auto accumC = torch::zeros({H * W, 3}, o);
    auto accumW = torch::zeros({H * W, 1}, o);
    accumC.scatter_add_(0,
        idxFlat.unsqueeze(1).expand({N * K * K, 3}), src);
    accumW.scatter_add_(0,
        idxFlat.unsqueeze(1), wFlat.unsqueeze(1));

    auto out = accumC / (accumW + 1e-6f);   // [H*W, 3]
    return out.reshape({H, W, 3}).clamp(0.f, 1.f);
}

} // namespace

// =========================================================================
// PointCloudBA
// =========================================================================

PointCloudBA::PointCloudBA() {
    status.running = false;
    status.initialized = false;
}

PointCloudBA::~PointCloudBA() { reset(); }

void PointCloudBA::allocParams(int64_t N) {
    auto o = opts();
    tPosition = torch::zeros({N, 3}, o).set_requires_grad(config.optimizePosition);
    tColor    = torch::zeros({N, 3}, o).set_requires_grad(config.optimizeColor);
    // log-space isotropic scale -> exp() in render gives the world radius.
    tScale    = torch::full({N, 1}, std::log(config.initScale), o);
    // logit of initOpacity (frozen — not optimized in the minimal prototype).
    float p = std::clamp(config.initOpacity, 1e-3f, 1.f - 1e-3f);
    tOpacity  = torch::full({N, 1}, std::log(p / (1.f - p)), o);

    cachedN = N;
}

void PointCloudBA::freeParams() {
    tPosition.reset();
    tColor.reset();
    tScale.reset();
    tOpacity.reset();
    tTarget.reset();
    tView.reset();
    optPosition.reset();
    optColor.reset();
    cachedN = 0;
}

bool PointCloudBA::init(const PointData& pd, const BACamera& cam,
                        const uint8_t* targetRGB) {
    if (pd.count == 0 || pd.position == nullptr || pd.color == nullptr) {
        println("PointCloudBA::init: empty point cloud (count={})", pd.count);
        return false;
    }
    if (cam.width <= 0 || cam.height <= 0 || targetRGB == nullptr) {
        println("PointCloudBA::init: invalid target ({}x{})", cam.width, cam.height);
        return false;
    }

    freeParams();
    int64_t N = int64_t(pd.count);
    allocParams(N);

    // --- Source the point cloud from the device buffers (zero-copy read) ---
    {
        auto posView = torch::from_blob(
            pd.position, {N, 3},
            {3 * sizeof(float), sizeof(float)}, opts());
        tPosition.copy_(posView);
        tPosition.set_requires_grad(config.optimizePosition);
    }
    // color: uint32 RGBA8 packed (0xAABBGGRR on little-endian — see
    // SNOrbbec::loadPointCloud which writes rgba[0..2]=r,g,b then 0xff).
    {
        auto colU32 = torch::from_blob(
            pd.color, {N}, {sizeof(uint32_t)},
            TensorOptions().dtype(torch::kUInt32).device(torch::kCUDA));
        auto r = (colU32                  & 0xff).to(torch::kFloat32) / 255.f;
        auto g = (torch::bitwise_right_shift(colU32, 8)  & 0xff).to(torch::kFloat32) / 255.f;
        auto b = (torch::bitwise_right_shift(colU32, 16) & 0xff).to(torch::kFloat32) / 255.f;
        tColor = torch::stack({r, g, b}, /*dim=*/1)
                     .set_requires_grad(config.optimizeColor);
    }

    // --- Target image: HxWx3 float in [0,1] on CUDA ---
    {
        int64_t H = cam.height, W = cam.width;
        auto tHost = torch::from_blob(
            const_cast<uint8_t*>(targetRGB),
            {H, W, int64_t(3)},
            {W * 3, int64_t(3), int64_t(1)},
            TensorOptions().dtype(torch::kUInt8));
        tTarget = tHost.to(torch::kFloat32).to(torch::kCUDA) / 255.f;
    }

    // --- Camera view matrix ---
    {
        auto vHost = torch::from_blob(
            const_cast<float*>(cam.view),
            {int64_t(4), int64_t(4)},
            {int64_t(4 * sizeof(float)), int64_t(sizeof(float))},
            TensorOptions().dtype(torch::kFloat32));
        tView = vHost.to(torch::kCUDA);
    }
    cachedFx = cam.fx; cachedFy = cam.fy;
    cachedCx = cam.cx; cachedCy = cam.cy;
    cachedW  = cam.width; cachedH = cam.height;

    // --- Optimizers (one per parameter group so lr can differ) ---
    if (config.optimizePosition) {
        optPosition = std::make_unique<torch::optim::AdamW>(
            std::vector<torch::Tensor>{tPosition},
            torch::optim::AdamWOptions(config.lrPosition));
    }
    if (config.optimizeColor) {
        optColor = std::make_unique<torch::optim::AdamW>(
            std::vector<torch::Tensor>{tColor},
            torch::optim::AdamWOptions(config.lrColor));
    }

    status.pointCount = int(N);
    status.targetW = cam.width;
    status.targetH = cam.height;
    status.step = 0;
    status.loss = 0.f;
    status.initialized = true;
    status.running = true;
    println("PointCloudBA::init: N={}, target={}x{}, lrPos={}, lrCol={}",
            N, cam.width, cam.height, config.lrPosition, config.lrColor);
    return true;
}

int PointCloudBA::step(PointData& pd, CUstream stream, int steps) {
    if (!status.initialized || !status.running) return 0;
    if (steps <= 0 || cachedN == 0) return 0;

    // For the prototype, run on libtorch's default CUDA stream. SN4DGSSplats
    // does the same — it relies on the shared primary context (libtorch
    // device 0 == Splatshop's CUDA context). We synchronize the host stream
    // before the D2D copies back into the render buffers so the writes are
    // visible to the forward-only renderer's next launch on `stream`.

    // Screen-space pixel radius for the splat patch. With a fixed initScale
    // and frozen scale/opacity, sigma_screen is constant; use a 3-sigma
    // radius. Clamp to a sane upper bound to bound memory.
    auto sigmaScreenHost = (tScale.exp() * (cachedFx / 1.f)).clamp_min(1e-3f);
    float maxSigma = sigmaScreenHost.max().item<float>();
    int pixelRadius = std::max(1, std::min(16, int(std::ceil(3.f * maxSigma))));

    auto runStep = [&]() {
        if (optPosition) optPosition->zero_grad();
        if (optColor)    optColor->zero_grad();

        auto pred = renderGaussians(
            tPosition, tColor, tScale, tOpacity, tView,
            cachedFx, cachedFy, cachedCx, cachedCy, cachedW, cachedH,
            pixelRadius);

        // L1 photometric loss.
        auto l1 = torch::abs(pred - tTarget).mean();

        // SSIM loss (averaged over 3 channels).
        Tensor ssimLoss;
        {
            int win = std::min(config.ssimWindow,
                               std::min(cachedW, cachedH));
            if (win % 2 == 0) win -= 1;
            if (win < 3) win = 3;
            auto pC = pred.permute({2, 0, 1});     // [3,H,W]
            auto tC = tTarget.permute({2, 0, 1});
            auto s0 = ssimSingleChannel(pC[0], tC[0], win, 1.5f);
            auto s1 = ssimSingleChannel(pC[1], tC[1], win, 1.5f);
            auto s2 = ssimSingleChannel(pC[2], tC[2], win, 1.5f);
            ssimLoss = 1.f - (s0 + s1 + s2) / 3.f;
        }

        auto loss = config.lambdaL1 * l1 + config.lambdaSSIM * ssimLoss;
        loss.backward();

        if (optPosition) optPosition->step();
        if (optColor)    optColor->step();

        status.step    += 1;
        status.loss     = loss.item<float>();
        status.lossL1   = l1.item<float>();
        status.lossSSIM = ssimLoss.item<float>();
    };

    int done = 0;
    for (int s = 0; s < steps; ++s) {
        if (status.step >= config.maxSteps) break;
        runStep();
        done += 1;
    }

    // --- Write refined position + color back into the render buffers ---
    // The forward-only renderer reads pd.position (vec3*) and pd.color
    // (uint32 RGBA8) directly; keep them in sync with the optimized tensors.
    //
    // libtorch runs backward()/step() on its own (default) CUDA stream, while
    // `stream` here is the app's non-blocking mainstream. Without fencing,
    // the D2D copy below could race with the in-flight autograd writes on the
    // source tensors. Record an event on libtorch's current stream and make
    // `stream` wait on it so the copies read fully-updated data.
    auto torchStream = c10::cuda::getCurrentCUDAStream();
    CUevent ev;
    CURuntime::check(cuEventCreate(&ev, CU_EVENT_DISABLE_TIMING));
    CURuntime::check(cuEventRecord(ev, torchStream.stream()));
    CURuntime::check(cuStreamWaitEvent(stream, ev, 0));
    CURuntime::check(cuEventDestroy(ev));

    if (config.optimizePosition && pd.position != nullptr) {
        auto posOut = tPosition.detach().contiguous();
        CURuntime::check(cuMemcpyDtoDAsync(
            reinterpret_cast<CUdeviceptr>(pd.position),
            reinterpret_cast<CUdeviceptr>(posOut.data_ptr<float>()),
            cachedN * 3 * sizeof(float), stream));
    }
    if (config.optimizeColor && pd.color != nullptr) {
        // Repack float rgb -> uint32 RGBA8 (0xAABBGGRR little-endian).
        auto c = (tColor.detach().clamp(0.f, 1.f) * 255.f).to(torch::kUInt8);
        auto r = c.index({torch::indexing::Slice(), 0}).to(torch::kUInt32);
        auto g = c.index({torch::indexing::Slice(), 1}).to(torch::kUInt32);
        auto b = c.index({torch::indexing::Slice(), 2}).to(torch::kUInt32);
        // Use bitwise_left_shift/left_shift ops — Tensor overloads operator<<
        // / operator>> for elementwise shift, but the int-literal forms
        // resolve ambiguously on MSVC, so call the explicit ops.
        auto packed = (torch::full({r.size(0)}, 0xffu << 24, opts().dtype(torch::kUInt32))
                       | torch::bitwise_left_shift(b, 16)
                       | torch::bitwise_left_shift(g, 8)
                       | r).contiguous();
        CURuntime::check(cuMemcpyDtoDAsync(
            reinterpret_cast<CUdeviceptr>(pd.color),
            reinterpret_cast<CUdeviceptr>(packed.data_ptr<uint32_t>()),
            cachedN * sizeof(uint32_t), stream));
    }

    if (status.step >= config.maxSteps) {
        status.running = false;
        println("PointCloudBA: reached maxSteps={}, stopping.", config.maxSteps);
    }

    return done;
}

void PointCloudBA::reset() {
    freeParams();
    status.initialized = false;
    status.running = false;
    status.step = 0;
    status.loss = 0.f;
}

} // namespace optim

#endif // SPLATSHOP_HAS_LIBTORCH
